### ISSUE TITLE
Switch out LangevinIntegrator for LangevinMiddleIntegrator

### ISSUE THREAD

**Issue by daveminh** [CCBatIIT/FultonMarket#1]
https://github.com/CCBatIIT/FultonMarket/blob/e65260cfc205672d0920fb62dc68a8efe462b4fb/FultonMarket.py#L66

**Comment by davidcooper7** [comment]
This is a dummy integrator to acquire the openmm context.

**Comment by josephdepaoloboisvert** [comment]
The actual integrator for replica exchange is located in Randolph.py
The MCMC move referenced below does use the LangevinMiddleIntegrator
https://github.com/CCBatIIT/FultonMarket/blob/e65260cfc205672d0920fb62dc68a8efe462b4fb/Randolph.py#L181
https://openmmtools.readthedocs.io/en/stable/api/generated/openmmtools.mcmc.LangevinDynamicsMove.html
