### ISSUE TITLE
Issue with Reshaping Array in apo Simulation

### ISSUE THREAD

**Issue by davidcooper7** [CCBatIIT/FultonMarket#10]
Hi David,

I hope you're doing well! I ran into an issue while running the simulation for the apo system. I got the following error:
![Screenshot 2024-12-10 095019](https://github.com/user-attachments/assets/161ed245-7d05-4b6a-9eb2-340136176779)

The input files (like apo.pdb, apo_sys.xml, and apo_state.xml) are located in the equil_output folder:
/expanse/lustre/projects/iit122/akhan3/5HT2A/equil_output/
If the simulation runs as expected, the results will be written to the replica_exchange directory: (output file)
/expanse/lustre/projects/iit122/akhan3/5HT2A/replica_exchange/

This is the correct location for this issue @aimankhan131

**Comment by davidcooper7** [comment]
I was able to reproduce this issue and find a solution. The n_replicates provided in the input script was not being modified based on reading the positions from the previous sub_simulation. This behavior has been fixed in f9604f1edcbdc3f6585d296db32608877cdd7275

**Comment by aimankhan131** [comment]
Ok, thank you so much. @davidcooper7
