### ISSUE TITLE
Issue with 6wha Simulation Output

### ISSUE THREAD

**Issue by aimankhan131** [CCBatIIT/FultonMarket#11]
Hi @davidcooper7 
I hope you're doing well.

I’m facing an issue with the 6wha simulation where it crashes while trying to save the output file. The error says the variable pos isn’t properly initialized in the truncate_ncdf function.
![image](https://github.com/user-attachments/assets/5bc13ee8-137f-4398-9d6c-6239040d6cb0)
Thankyou.

**Comment by davidcooper7** [comment]
It appears you have an empty save directory and corrupted output.ncdf file. 

Please try deleting the directory /expanse/lustre/projects/iit122/akhan3/5HT2A/replica_exchange/6wha_0/saved_variables/18 and delete the *.ncdf files in /expanse/lustre/projects/iit122/akhan3/5HT2A/replica_exchange/6wha_0 

Then try resuming the simulation.

**Comment by aimankhan131** [comment]
Ok, I will do. Thankyou so much, @davidcooper7

**Comment by davidcooper7** [comment]
Did this work @aimankhan131 ?

**Comment by aimankhan131** [comment]
Yes, it worked because the job has been running since yesterday, but I'll monitor it until it's completion to see if I encounter any errors or not and will let you know @davidcooper7
