### ISSUE TITLE
Remove minimization after state insertion

### ISSUE THREAD

**Issue by daveminh** [CCBatIIT/FultonMarket#5]
Going from minimized structures directly to high temperatures regularly causes NaN errors. It is unnecessary to minimize as resampled structures should be from the Boltzmann distribution.

**Comment by daveminh** [comment]
Can you do this ASAP so I can put it in the class exercise? I pushed back the class session discussing the exercise to next Monday, but would like to have the exercise available sooner so students can get calculations started.

**Comment by davidcooper7** [comment]
This issue has been fixed with e18d527d88e8b03e215e66a5c68925ba4ae994f0
