### ISSUE TITLE
if resids argument is None, self.resids is undefined

### ISSUE THREAD

**Issue by daveminh** [CCBatIIT/FultonMarket#8]
Should add the following

'''
else:
  self.resids = None
'''

https://github.com/CCBatIIT/FultonMarket/blob/e18d527d88e8b03e215e66a5c68925ba4ae994f0/FultonMarket/analysis/FultonMarketAnalysis.py#L49

**Comment by davidcooper7** [comment]
This was fixed in an earlier commit. Not going to track down the commit id.
